In [7]:
# loading the library
import pandas as pd

train = pd.read_csv('C:\\Users\\CDT WO AZEEZ SAMAD\\Downloads\\climate-health-prediction\\data\\Train.csv')
test = pd.read_csv('C:\\Users\\CDT WO AZEEZ SAMAD\\Downloads\\climate-health-prediction\\data\\Test.csv')
features = pd.read_csv('C:\\Users\\CDT WO AZEEZ SAMAD\\Downloads\\climate-health-prediction\\data\\climate_features.csv')

In [8]:
#checking the shape of the dataframes
print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Features shape:", features.shape)

Train shape: (3146, 13)
Test shape: (1030, 12)
Features shape: (4176, 18)

In [9]:
#displaying the first few rows of the dataframes
print("\nTrain DataFrame:")
display(train.head())
print("\nTest DataFrame:")
display(test.head())
print("\nFeatures DataFrame:")
display(features.head())

Train DataFrame:

,ID,zone,gender,deathdate,age,avg_temperature,max_temperature,min_temperature,precipitation,latitude,longitude,location,is_climate_sensitive
0,ID_1FE951BD,Rural,Male,10/2/2007,30,21.137037,25.569017,18.451642,0.951601,0.584646,33.546344,"Izimba, Iganga, Uganda",1
1,ID_5927A443,Rural,Male,1/5/2008,2,24.062790,29.312026,18.977212,0.053352,0.549565,33.490326,"Nawanzu, Iganga, Uganda",1
2,ID_C4E67025,Rural,Female,2/14/2008,31,22.407868,26.746058,18.112977,0.090349,0.573420,33.483655,"Buluza, Iganga, Uganda",1
3,ID_44DC5CE9,Rural,Female,2/15/2008,1,23.315198,28.056889,18.955708,0.286814,0.549565,33.490326,"Nawanzu, Iganga, Uganda",1
4,ID_33C677BB,Rural,Female,2/15/2008,69,23.315198,28.056889,18.955708,0.286814,1.072343,34.226647,"Magada, Mbale City, Bugisa sub-region, Eastern...",0

Test DataFrame:

,ID,zone,gender,deathdate,age,avg_temperature,max_temperature,min_temperature,precipitation,latitude,longitude,location
0,ID_E760D84B,Rural,Female,2007-11-24,75.0,21.224387,24.632729,18.145633,4.295335,0.616667,33.500000,"Buseyi, Iganga, Uganda"
1,ID_6EDEA907,Rural,Female,2008-01-23,50.0,21.708596,25.184528,18.285274,1.376196,0.725422,33.098845,"Bubago, Kamuli, Uganda"
2,ID_B9FFC8D8,Rural,Female,2008-03-14,76.0,21.371149,24.584523,18.866490,2.336643,0.603194,33.542370,"Busowobi Central, Iganga, Uganda"
3,ID_74C6C94E,Peri_urban,Female,2008-04-16,90.0,21.341990,25.188662,17.998317,4.703071,-0.590211,30.056939,"Kayanga, Mitooma, Western Region, Uganda"
4,ID_0E02825D,Rural,Male,2008-04-21,8.0,19.710391,22.905167,18.082628,4.066863,0.603194,33.542370,"Busowobi Central, Iganga, Uganda"

Features DataFrame:

,ID,deathdate,elevation,hot_days_30d,max_daily_rain_30d,ndvi_30d,ndvi_90d,rain_days_30d,rain_sum_30d,rain_sum_7d,rain_sum_90d,slope,tavg_30d,tavg_7d,tavg_90d,temp_range_mean_30d,tmax_30d,tmin_30d
0,ID_1FE951BD,2007-10-02,1114,0,20.394434,0.72205,0.72910,18,175.264057,28.419111,421.992750,0.168545,21.425953,22.012127,21.043539,7.897970,27.608331,16.132043
1,ID_5927A443,2008-01-05,1145,0,16.994602,0.60815,0.66985,7,71.885960,0.000000,268.439276,0.299996,22.129209,23.021381,21.992129,8.735769,29.251932,15.591455
2,ID_C4E67025,2008-02-14,1145,0,15.661628,0.59290,0.61335,20,108.145379,35.970423,242.081887,0.299996,21.990516,21.557252,22.220307,7.694241,29.083597,17.420068
3,ID_44DC5CE9,2008-02-15,1145,0,15.661628,0.59290,0.61335,19,98.524518,29.091067,229.370640,0.299996,22.032392,21.693581,22.231408,7.718027,29.083597,17.420068
4,ID_33C677BB,2008-02-15,1660,0,13.468142,0.53380,0.71580,13,84.030272,25.698621,186.079130,5.565486,20.143552,20.141416,20.510054,10.152887,28.300394,12.632257

In [10]:
#checking the column names of the dataframes
print("Train Columns")
display(train.columns.tolist())
print("Test Columns")
display(test.columns.tolist())
print("Features Columns")
display(features.columns.tolist())

Train Columns

['ID',
 'zone',
 'gender',
 'deathdate',
 'age',
 'avg_temperature',
 'max_temperature',
 'min_temperature',
 'precipitation',
 'latitude',
 'longitude',
 'location',
 'is_climate_sensitive']

Test Columns

['ID',
 'zone',
 'gender',
 'deathdate',
 'age',
 'avg_temperature',
 'max_temperature',
 'min_temperature',
 'precipitation',
 'latitude',
 'longitude',
 'location']

Features Columns

['ID',
 'deathdate',
 'elevation',
 'hot_days_30d',
 'max_daily_rain_30d',
 'ndvi_30d',
 'ndvi_90d',
 'rain_days_30d',
 'rain_sum_30d',
 'rain_sum_7d',
 'rain_sum_90d',
 'slope',
 'tavg_30d',
 'tavg_7d',
 'tavg_90d',
 'temp_range_mean_30d',
 'tmax_30d',
 'tmin_30d']

In [11]:
#checking for duplicates in the dataframes
print("Train Duplicates:", train.duplicated("ID").sum())
print("Test Duplicates:", test.duplicated("ID").sum())
print("Features Duplicates:", features.duplicated("ID").sum())

Train Duplicates: 0
Test Duplicates: 0
Features Duplicates: 0

In [12]:
#  Check missing values
print("\nMissing values in Train:")
display(train.isnull().sum().sort_values(ascending=False).head(15))

print("\nMissing values in Test:")
display(test.isnull().sum().sort_values(ascending=False).head(15))

print("\nMissing values in Features:")
display(features.isnull().sum().sort_values(ascending=False).head(15))

Missing values in Train:

ID                      0
zone                    0
gender                  0
deathdate               0
age                     0
avg_temperature         0
max_temperature         0
min_temperature         0
precipitation           0
latitude                0
longitude               0
location                0
is_climate_sensitive    0
dtype: int64

Missing values in Test:

ID                 0
zone               0
gender             0
deathdate          0
age                0
avg_temperature    0
max_temperature    0
min_temperature    0
precipitation      0
latitude           0
longitude          0
location           0
dtype: int64

Missing values in Features:

ID                     0
deathdate              0
tmax_30d               0
temp_range_mean_30d    0
tavg_90d               0
tavg_7d                0
tavg_30d               0
slope                  0
rain_sum_90d           0
rain_sum_7d            0
rain_sum_30d           0
rain_days_30d          0
ndvi_90d               0
ndvi_30d               0
max_daily_rain_30d     0
dtype: int64

In [13]:
# investigating target variable distribution in the train dataset
print("\nTarget variable distribution in Train:")
display(train["is_climate_sensitive"].value_counts())

print("\nTarget proportions:")
display(train["is_climate_sensitive"].value_counts(normalize=True))

Target variable distribution in Train:

is_climate_sensitive
1    2047
0    1099
Name: count, dtype: int64

Target proportions:

is_climate_sensitive
1    0.650668
0    0.349332
Name: proportion, dtype: float64

In [16]:
# Check whether every train ID exists in features
train_ids_match = train["ID"].isin(features["ID"]).all()
print("\nDo all Train IDs exist in Features?", train_ids_match)

Do all Train IDs exist in Features? True